image: rust:1.94.1-alpine3.23

stages:
  - test
  - validate
.setup_deps: &setup_deps
  - apk add --no-cache pkgconfig openssl-dev musl-dev gcc make perl


validate-syntax-errors:
  stage: test
  before_script:
    - *setup_deps
  script:
    - cargo check --workspace --all-features
validate_tests:
  stage: test
  before_script:
    - *setup_deps
  script:
    - cargo test --workspace --all-features

validate-format-check-and-lint:
  stage: validate
  before_script:
    - *setup_deps
    - rustup component add clippy rustfmt
  script:
    - cargo clippy --workspace --all-features --all-targets -- -D warnings
    - cargo fmt --all -- --check
