image: rust:1.94.1-alpine3.23

stages:
  - validate

format-check-and-lint:
  stage: validate
  before_script:
    - apk add --no-cache pkgconfig openssl-dev musl-dev
    - rustup component add clippy
  script:
    - cargo clippy --workspace --all-features --all-targets -- -D warnings
    - cargo fmt --all -- --check
