image: rust:1.94.1-alpine3.23

stages:
  - test
  - validate

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo/
    - target/
  policy: pull-push

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

validate-syntax-errors:
  stage: test
  script:
    - cargo check --workspace --all-features

validate_tests:
  stage: validate
  script:
    - cargo test --workspace --all-features
  cache:
    <<: *global_cache
    policy: pull

validate-format-check-and-lint:
  stage: validate
  before_script:
    - rustup component add clippy rustfmt
  script:
    - cargo clippy --workspace --all-features --all-targets -- -D warnings
    - cargo fmt --all -- --check
  cache:
    <<: *global_cache
    policy: pull
